// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTQp2d2sPz5y3wudd1jNlGkUzoou3B-I',
    appId: '1:939633534168:web:71368a3fa03015972b63ad',
    messagingSenderId: '939633534168',
    projectId: 'esquadifi-72d81',
    authDomain: 'esquadifi-72d81.firebaseapp.com',
    storageBucket: 'esquadifi-72d81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsRqwyGUDLjUV1Yv23r0UpSlsyE-DWvo8',
    appId: '1:939633534168:android:335dd9f597cde3972b63ad',
    messagingSenderId: '939633534168',
    projectId: 'esquadifi-72d81',
    storageBucket: 'esquadifi-72d81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnCgbxSRzJ7M9RJsyD8mHo49WBeHhCm7g',
    appId: '1:939633534168:ios:43cf3edcfd3314962b63ad',
    messagingSenderId: '939633534168',
    projectId: 'esquadifi-72d81',
    storageBucket: 'esquadifi-72d81.appspot.com',
    iosBundleId: 'com.example.eSquadifi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnCgbxSRzJ7M9RJsyD8mHo49WBeHhCm7g',
    appId: '1:939633534168:ios:43cf3edcfd3314962b63ad',
    messagingSenderId: '939633534168',
    projectId: 'esquadifi-72d81',
    storageBucket: 'esquadifi-72d81.appspot.com',
    iosBundleId: 'com.example.eSquadifi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKTQp2d2sPz5y3wudd1jNlGkUzoou3B-I',
    appId: '1:939633534168:web:5d724e08d54c16a32b63ad',
    messagingSenderId: '939633534168',
    projectId: 'esquadifi-72d81',
    authDomain: 'esquadifi-72d81.firebaseapp.com',
    storageBucket: 'esquadifi-72d81.appspot.com',
  );
}
